dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure:
        uw61JIM9NdFFUAyqJZvf7rjmsoKlpLatR2WIkeOnJdUoX+zfvzuoRQ8E7ywjT7uHQIziDpV9KN37GbCFyX0Kbepi4+3vL1Khl6hydQ9yf34dr7FN5KWQSo7N5Qnt90+rVvi6cUm/Dmgl0yHJC3B4LWV9ZXgJ5WicDmAttJnYYVLUbU/6w8E/P7bPvN91BPvAapjoTiHZNpTLgYFw4TsQuUSEBxH3ZiyHXdURCwH8hNAT3VMv8r2hcxBnxuwGs9HtL25s7QUP2kIxdWBFy5U/28J3di4TuMLE/zb7XOAm0r5jQBuLkUHg45YQANkcZ/BWt+H0DfQWmsKQAMSNOx1zCuZkAwbxqz+WSkYBeZiJxwPk0TeZ2DZfUaFr8BUoAjW7YMVFaiVzNNpg8MAW8CYewpfWBnjn9Udf9YVjHQAuLXcvf5xGW5zL91aopiNfwT6EmwHAdWCUwItu35ct2fbJLGjCCj/5AQqMqY9bEdPAkUfAmGUKdrH1ckt0l2k8VWKskzvCssZVekVC9/jUk4/55wGvn/Ago815SwESg2qgM/6ZIcZ8JCUvIpmzImZEFj9cdVzsqD1aHzIBv8zbRq5Gik1J1NjvkHTIZPKN7No31uAnp9Td1N4SZ4cVqurU6RXU87Dbj6z4yVQfAvQ+vxJfTEXB7ppHRcpR5krFuxSEDA0=
